version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - private-net

  streamlit:
    build: /home/endre/photoneo_ws/src/micro_sp_ui/
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - private-net

# Define the custom network used by all services
networks:
  private-net:
    driver: bridge