services:
  redis:
    image: redis:latest
    container_name: redis
    ports: # Only when running nativelly with cargo run
      # - "127.0.0.1:6379:6379"
      - "6379:6379"
    networks:
      - private-net

  micro_sp_ui:
    build: ./micro_sp_ui/docker
    container_name: micro_sp_ui
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - private-net
    
  # dockursim: 
  #   build: ./ursim/docker
  #   container_name: dockursim
  #   environment:
  #     - ROBOT_MODEL=UR10 
  #   ports:
  #     - "3000:3000"
  #     - "29999:29999"
  #     - "30001-30004:30001-30004"
  #   networks:
  #     - private-net

networks:
  private-net:
    driver: bridge